# Export files for direct inclusion in other cc_library targets
exports_files([
    "duplex_shm_transport.cpp",
    "duplex_shm_transport.hpp",
], visibility = ["//visibility:public"])

cc_library(
    name = "duplex_shm_transport",
    srcs = [
        "duplex_shm_transport.cpp",
    ],
    hdrs = [
        "duplex_shm_transport.hpp",
    ],
    copts = ["-std=c++17"],
    include_prefix = "shared_memory",
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        "@boost.asio",
        "@boost.interprocess",
    ],
)

cc_binary(
    name = "duplex_shm_transport_demo",
    srcs = ["duplex_shm_transport_demo.cpp"],
    linkopts = [
        "-pthread",
        "-lrt",
    ],
    deps = [":duplex_shm_transport"],
)
